### ISSUE TITLE
DHT11 sensor results  Expected 84 but got 0 pulses

### ISSUE THREAD

**Issue by MrBanane6969** [sunfounder/kepler-kit#2]
Traceback (most recent call last):
  File "<stdin>", line 9, in <module>
  File "dht.py", line 57, in measure
InvalidPulseCount: Tried 5 times, but all failed
[Try 0] Expected 84 but got 0 pulses
[Try 1] Expected 84 but got 0 pulses
[Try 2] Expected 84 but got 0 pulses
[Try 3] Expected 84 but got 0 pulses
[Try 4] Expected 84 but got 0 pulses       

Changed Sensor to another sensor. same error.        instructions on site unclear.

**Comment by MrBanane6969** [comment]
instructions found.


Cleared.
